# Generated by Django 4.0.6 on 2022-12-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_quizjour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizjour',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
