# Generated by Django 4.0.6 on 2022-12-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_quizjour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsjour',
            name='indication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
