# Generated by Django 4.1.6 on 2023-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_alter_questionsjour_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsjour',
            name='image',
            field=models.FileField(blank=True, upload_to='imagequestion'),
        ),
        migrations.AlterField(
            model_name='questionsjour',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
