"""
Django settings for tensorflow2 project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2gue6+fxnb85#6k)0mw%rwcr$+w7lnz@=g3@ch-lkve8-iy8#@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# '192.168.43.120'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'connex',
    'comment',
    'programme',
    'Quiz',
]
X_FRAME_OPTIONS = 'SAMEORIGIN' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tensorflow2.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tensorflow2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
STATICFILES_DIRS =[
    os.path.join(BASE_DIR,"static")
]
CKEDITOR_UPLOAD_PATH= 'uploads/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'connex.User'
PHONENUMBER_DB_FORMAT='NATIONAL'
PHONENUMBER_DEFAULT_REGION='BF'

#LIGIDICASH KEY
LIGIDICASH_API_KEY= '3AQYSL8UGXVS0U39Z'
LIGIDICASH_TOKEN_KEY= 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZF9hcHAiOiI3NzQiLCJpZF9hYm9ubmUiOjg5OTQyLCJkYXRlY3JlYXRpb25fYXBwIjoiMjAyMi0xMS0yNCAyMzo1NjowMCJ9.DjcOWYQH6JKPmGUnsaNq6LLDJACJws5ct-lhT3bABxE'
#CINET PAY KEYS
CINETPAY_API_KEY='196802189063fe932c167133.93989100'
CINETPAY_SITE_ID='750722'
SECRET_KEY='119472365640db9f10fbdd3.70724153'



# CKEDITOR_CONFIGS = {
#     'default':{
#         'toolbar': 'Custom',
#         'toolbar_Custom':[
            
#             ['Bold','Italic','Underline','Image','Table','Styles','Format','Font','FontSize',],           
#             ],
#         'height': 'auto',
#         'width': 'auto',
#         'enterMode': 2,
#         # 'config.autoParagraph':False,
#         # 'CKEDITOR.config.enterMode': 'CKEDITOR.ENTER_BR',
#         # 'CKEDITOR.config.shiftEnterMode': 'CKEDITOR.ENTER_P',
#     },
# }

CKEDITOR_CONFIGS = {
    'default':{
        'toolbar': None,
        'enterMode': 2,
        'height': 'auto',
        'width': 'auto',

    },
}

EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS= True
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='zaideelearning@gmail.com'
EMAIL_HOST_PASSWORD='vqiszeuwwquwbieu'
EMAIL_PORT= 587 



import django
from django.utils.encoding import force_str
django.utils.encoding.force_text= force_str


