# Generated by Django 4.0.6 on 2022-11-10 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_niveau', models.CharField(blank=True, max_length=200, null=True)),
                ('image_niveau', models.FileField(blank=True, null=True, upload_to='classe')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_matiere', models.CharField(blank=True, max_length=200, null=True)),
                ('image_matiere', models.FileField(blank=True, null=True, upload_to='Matirer')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('matiere_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere', to='programme.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Lecons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_lecon', models.CharField(blank=True, max_length=100, null=True)),
                ('lecon_pdf', models.FileField(blank=True, null=True, upload_to='lecons_pdf', verbose_name='lecon_pdf')),
                ('numero_lecon', models.PositiveIntegerField(blank=True, null=True, verbose_name='chapitre no')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('lecon_matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecon', to='programme.matiere')),
                ('lecon_niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.niveau')),
            ],
            options={
                'ordering': ['numero_lecon'],
            },
        ),
        migrations.CreateModel(
            name='Exercices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Exercices', models.CharField(blank=True, max_length=200, null=True)),
                ('exercices', models.FileField(blank=True, null=True, upload_to='exercices', verbose_name='exercices')),
                ('exercices_corrige', models.FileField(blank=True, null=True, upload_to='exercices_corrigés', verbose_name='exercices_corrigés')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('exercices_lecons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='programme.lecons')),
                ('exercices_matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.matiere')),
                ('exercices_niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.niveau')),
            ],
        ),
    ]
