# Generated by Django 4.0.6 on 2022-11-12 01:49

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomQuiz', models.CharField(max_length=300)),
                ('numeroQuiz', models.IntegerField(help_text='Questionnaire Numero')),
                ('nombreDequestion', models.IntegerField(help_text='nombre de question')),
                ('temps', models.IntegerField(help_text='temps pour traiter le questionnair')),
                ('score', models.IntegerField(help_text='Point pour le questionnaire')),
                ('dificulte', models.CharField(choices=[('Facile', 'Facile'), ('Normal', 'Normal'), ('Difficile', 'Dificle')], max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('matierequiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuizMatiere', to='programme.matiere')),
                ('niveauQuiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='score obtenu par l utilisateur')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReponsesQUiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='programme.questionquiz')),
            ],
        ),
        migrations.AddField(
            model_name='questionquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='programme.quiz'),
        ),
    ]
