# Generated by Django 4.0.6 on 2022-11-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_questionquiz_quiz_resultats_reponsesquiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionquiz',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
