# Generated by Django 4.0.6 on 2022-11-13 02:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_alter_questionquiz_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionquiz',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reponsesquiz',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
