# Generated by Django 4.0.6 on 2022-11-14 02:17

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_alter_reponsesquiz_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionquiz',
            name='text',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
