# Generated by Django 4.0.6 on 2022-11-14 09:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0013_alter_questionquiz_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionquiz',
            name='contenue',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
