# Generated by Django 4.0.6 on 2022-11-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0014_questionquiz_contenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionquiz',
            name='contenue',
        ),
    ]
