# Generated by Django 4.0.6 on 2022-11-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0017_alter_questionquiz_text_alter_reponsesquiz_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionquiz',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reponsesquiz',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
