# Generated by Django 4.0.6 on 2022-11-20 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme', '0019_favoris'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gquiz', to='programme.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Generalquiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomQuiz', models.CharField(max_length=300)),
                ('numeroQuiz', models.IntegerField(help_text='Questionnaire Numero')),
                ('nombreDequestion', models.IntegerField(help_text='nombre de question')),
                ('temps', models.IntegerField(help_text='temps pour traiter le questionnair')),
                ('score', models.IntegerField(help_text='Point pour le questionnaire')),
                ('dificulte', models.CharField(choices=[('Facile', 'Facile'), ('Normal', 'Normal'), ('Difficile', 'Dificle')], max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('niveauQuiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quizniveau', to='programme.niveau')),
            ],
        ),
        migrations.AlterModelOptions(
            name='resultats',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='GeneralResultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='score obtenu par l utilisateur')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.generalquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralReponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gquestion', to='programme.generalquestion')),
            ],
        ),
    ]
