# Generated by Django 4.0.6 on 2022-12-15 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme', '0024_lecons_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecons',
            name='Favoris',
        ),
        migrations.AddField(
            model_name='lecons',
            name='Favorislecon',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorislecon', to=settings.AUTH_USER_MODEL),
        ),
    ]
