# Generated by Django 4.0.6 on 2022-12-15 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme', '0025_remove_lecons_favoris_lecons_favorislecon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecons',
            name='Favorislecon',
        ),
        migrations.AddField(
            model_name='lecons',
            name='Favoris',
            field=models.ManyToManyField(blank=True, null=True, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
