# Generated by Django 4.0.6 on 2022-12-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0026_remove_lecons_favorislecon_lecons_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionquiz',
            name='indication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
