# Generated by Django 4.0.6 on 2022-12-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0027_questionquiz_indication'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalquestion',
            name='indication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
