# Generated by Django 4.1.6 on 2023-02-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0029_alter_resultats_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalresultats',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalQuiz', to='programme.generalquiz'),
        ),
    ]
