# Generated by Django 4.1.6 on 2023-02-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connex', '0006_alter_planadhesion_type_adhesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ceckbox_info',
            field=models.BooleanField(default=False),
        ),
    ]
