# Generated by Django 4.1.7 on 2023-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connex', '0008_remove_user_telphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='transaction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historique',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
