# Generated by Django 4.0.6 on 2022-11-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_commentaire_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='comment.informations'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='nomCom',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
